# Get all temples
GET http://localhost:8080/temples
apiKey: superSecretKey123

###

# Get a specific temple
GET http://localhost:8080/temples/1
apiKey: superSecretKey123

###

# Create a temple
POST http://localhost:8080/temples
Content-Type: application/json
apiKey: superSecretKey123

{
  "_id": "61a921f6028954d4f0319e6d",
  "temple_id": 1,
  "additionalInfo": false,
  "name": "Aba Nigeria Temple",
  "location": "Aba, Abia, Nigeria",
  "dedicated": "7 August 2005"
}

###

# Update a temple
PUT http://localhost:8080/temples/61a921f6028954d4f0319e6d
Content-Type: application/json
apiKey: superSecretKey123

{
  
  "temple_id": 1,
  "additionalInfo": false,
  "name": "Aba Nigeria Temple3",
  "location": "Aba, Abia, Nigeria",
  "dedicated": "7 August 2005"
}

###

# Delete a temple
DELETE http://localhost:8080/temples/61a921f6028954d4f0319e6d
apiKey: superSecretKey123

###

# Delete all temples
DELETE http://localhost:8080/temples
apiKey: superSecretKey123

###

# Get published temples
GET http://localhost:8080/temples/published
apiKey: superSecretKey123
